---
title: "R Notebook"
output:
  github_document:
    html_preview: true
---


```{r}
library(reticulate)
#library(usethis)

#use_python("/Users/ty/opt/miniconda3/bin/python")
#use_virtualenv("~/myenv")
#use_condaenv(condaenv = "r-nlp", conda = "/Users/ty/opt/miniconda3/envs/earth-analytics-python/opt/miniconda3")
#use_virtualenv("/Users/ty/opt/miniconda3/envs/earth-analytics-python/bin/python3")
py_config()
edit_r_environ()
```

```{python}
import pandas as pd
import geopandas
import matplotlib.pyplot as plt
import numpy as np
import plotnine
import contextily as cx
import requests
import json
```

https://www.neonscience.org/resources/learning-hub/tutorials/neon-api-01-introduction-requests



```{python}
metadata = pd.read_csv('data/NEON_Field_Site_Metadata_20220224.csv')
print(metadata.field_site_id)
```


```{r}
library(tidyverse)
library(sf)
library(maps)
```


```{r}
metadata_read = read.csv('data/NEON_Field_Site_Metadata_20220224.csv')

metatdata <- st_as_sf(metadata_read, coords = c("field_longitude", "field_latitude"), crs=4326)

bb <- st_bbox(metatdata)

usa <- st_as_sf(map_data("usa"), coords = c( "long", "lat"), crs=4326)

```

```{r}
ggplot() +
  geom_sf(data = usa, col="white") +
  geom_sf(data=metatdata,aes( color=field_avg_number_of_green_days), size=5) +
  coord_sf(xlim = c(bb[1], bb[3]), ylim = c(bb[2], bb[4]))
```

```{r}
terrestrial_sites <- metatdata %>% 
  filter(field_site_type == "Core Terrestrial" | field_site_type == "Gradient Terrestrial" ) 

as.data.frame(terrestrial_sites)
```
```{r}
ggplot() +
  geom_sf(data = usa, col="white") +
  geom_sf(data=terrestrial_sites,aes( color=field_avg_number_of_green_days), size=5) +
  coord_sf(xlim = c(bb[1], bb[3]), ylim = c(bb[2], bb[4]))
```

```{r}
box <- c(xmin = -130, ymin = 25, xmax = -100, ymax = 50)
west_us_terrestrial_neon_sites <- metatdata %>% 
  filter(field_site_type == "Core Terrestrial" | field_site_type == "Gradient Terrestrial" ) %>%
  st_crop(box)

as.data.frame(west_us_terrestrial_neon_sites)
```
```{r}
ggplot() +
  geom_sf(data = usa, col="white") +
  geom_sf(data=west_us_terrestrial_neon_sites,aes( color=field_avg_number_of_green_days), size=2) +
  coord_sf(xlim = c(box[1], box[3]), ylim = c(box[2], box[4]))
```

```{r}
west_us_terrestrial_Evergreen_neon_sites <- metatdata %>% 
  filter(field_site_type == "Core Terrestrial" | field_site_type == "Gradient Terrestrial" ) %>%
  filter(field_dominant_nlcd_classes !=  "Grassland/Herbaceous" & field_dominant_nlcd_classes !=  "Shrub/Scrub" & field_dominant_nlcd_classes != "Cultivated Crops") %>%
  st_crop(box)

as.data.frame(west_us_terrestrial_Evergreen_neon_sites)
```

```{r}
ggplot() +
  geom_sf(data = usa, col="white") +
  geom_sf(data=west_us_terrestrial_Evergreen_neon_sites,aes( color=field_mean_canopy_height_m), size=2) +
  coord_sf(xlim = c(box[1], box[3]), ylim = c(box[2], box[4]))
```


```{python}
SERVER = 'http://data.neonscience.org/api/v0/'
SITECODE = 'NIWO'

site_request = requests.get(SERVER+'sites/'+SITECODE)

#Convert to Python JSON object
site_json = site_request.json()
site_json.keys()

site_json['data'].keys()

site_json
```



```{python}
site_json['data'].keys()
```


```{python}
for product in site_json['data']['dataProducts']:
    print(product['dataProductCode'],product['dataProductTitle'])
    
```



```{python}

PRODUCTCODE = 'DP2.30011.001'
```


```{python}
#Get available months of Breeding Landbird Count data products for TEAK site
#Loop through the 'dataProducts' list items (each one a dict) at the site
for product in site_json['data']['dataProducts']: 
    if(product['dataProductCode'] == PRODUCTCODE): #If a list item's 'dataProductCode' dict element equals the product code string,
        print('Available Months: ',product['availableMonths']) #print the available months and URLs
        print('URLs for each Month: ', product['availableDataUrls'])
```


```{python}
#Make Request
data_request = requests.get(SERVER+'data/'+PRODUCTCODE+'/'+SITECODE+'/'+'2020-08')
data_json = data_request.json()

print(data_json)
```

```{r}
py$data_json
```



